### ISSUE TITLE
是不是少上传文件了

### ISSUE THREAD

**Issue by lvdong** [Linyuzai/concept#1]
Could not read script 'E:\workspace\concept\sonatype.gradle' as it does not exist

**Comment by Linyuzai** [comment]
这个是我发布包的密钥配置文件，你直接把publish.gradle里面的内容注释掉应该就行了

**Comment by lvdong** [comment]
好的。 现在能正常编译了。感谢！

**Comment by Linyuzai** [comment]
不客气
