### ISSUE TITLE
如何基于路径给某些用户推送

### ISSUE THREAD

**Issue by dagaozi** [Linyuzai/concept#10]
大神，你好，基于路径推送使用PathMessage可以实现，针对用户推送使用UserMesage可以实现，如何实现根据路径给某些用户推送啊，类似于这样: concept.send(new PathMessage(msg,path,listUserId))。如果我使用我自己定义一个消息类PathUserMessage，不知道 setBroadcast(false);是true，还是false。能否提供一个默认实现。

public class PathUserMessage extends ObjectMessage {
    public PathUserMessage(Object payload, String path,String... userIds) {
        this(payload,path, Arrays.asList(userIds));
    }

    public PathUserMessage(Object payload,String path, Collection<String> userIds) {
        super(payload);
        setBroadcast(false);
        getHeaders().put(PathSelector.KEY, path);
        getHeaders().put(UserSelector.KEY, String.join(",", userIds));
    }
}

**Comment by Linyuzai** [comment]
> 大神，你好，基于路径推送使用PathMessage可以实现，针对用户推送使用UserMesage可以实现，如何实现根据路径给某些用户推送啊，类似于这样: concept.send(new PathMessage(msg,path,listUserId))。如果我使用我自己定义一个消息类PathUserMessage，不知道 setBroadcast(false);是true，还是false。能否提供一个默认实现。
> 
> public class PathUserMessage extends ObjectMessage { public PathUserMessage(Object payload, String path,String... userIds) { this(payload,path, Arrays.asList(userIds)); }
> 
> ```
> public PathUserMessage(Object payload,String path, Collection<String> userIds) {
>     super(payload);
>     setBroadcast(false);
>     getHeaders().put(PathSelector.KEY, path);
>     getHeaders().put(UserSelector.KEY, String.join(",", userIds));
> }
> ```
> 
> }

`setBroadcast`用于标记本地服务如果匹配到之后是否还要转发到其他的实例，如果用户可以多端登录就设置为`true`，如果不行就设置`false`

另外你需要自己实现一个`ConnectionSelector`来适配你的消息，可以继承`AbstractConnectionSelector`，然后处理连接筛选，参考`PathSelector`和`PathSelector`，加个`Order`把顺序放到前面

**Comment by Linyuzai** [comment]
> > 大神，你好，基于路径推送使用PathMessage可以实现，针对用户推送使用UserMesage可以实现，如何实现根据路径给某些用户推送啊，类似于这样: concept.send(new PathMessage(msg,path,listUserId))。如果我使用我自己定义一个消息类PathUserMessage，不知道 setBroadcast(false);是true，还是false。能否提供一个默认实现。
> > public class PathUserMessage extends ObjectMessage { public PathUserMessage(Object payload, String path,String... userIds) { this(payload,path, Arrays.asList(userIds)); }
> > ```
> > public PathUserMessage(Object payload,String path, Collection<String> userIds) {
> >     super(payload);
> >     setBroadcast(false);
> >     getHeaders().put(PathSelector.KEY, path);
> >     getHeaders().put(UserSelector.KEY, String.join(",", userIds));
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > }
> 
> `setBroadcast`用于标记本地服务如果匹配到之后是否还要转发到其他的实例，如果用户可以多端登录就设置为`true`，如果不行就设置`false`
> 
> 另外你需要自己实现一个`ConnectionSelector`来适配你的消息，可以继承`AbstractConnectionSelector`，然后处理连接筛选，参考`PathSelector`和`PathSelector`，加个`Order`把顺序放到前面

参考`PathSelector`和`UserSelector`

**Comment by Linyuzai** [comment]
> 大神，你好，基于路径推送使用PathMessage可以实现，针对用户推送使用UserMesage可以实现，如何实现根据路径给某些用户推送啊，类似于这样: concept.send(new PathMessage(msg,path,listUserId))。如果我使用我自己定义一个消息类PathUserMessage，不知道 setBroadcast(false);是true，还是false。能否提供一个默认实现。
> 
> public class PathUserMessage extends ObjectMessage { public PathUserMessage(Object payload, String path,String... userIds) { this(payload,path, Arrays.asList(userIds)); }
> 
> ```
> public PathUserMessage(Object payload,String path, Collection<String> userIds) {
>     super(payload);
>     setBroadcast(false);
>     getHeaders().put(PathSelector.KEY, path);
>     getHeaders().put(UserSelector.KEY, String.join(",", userIds));
> }
> ```
> 
> }

2.0.0版本已经默认支持，[Wiki](https://github.com/Linyuzai/concept/wiki/Concept-WebSocket-LoadBalance-2#组合条件)
