### ISSUE TITLE
多线程问题

### ISSUE THREAD

**Issue by chuchushijingxi** [Linyuzai/concept#12]
大佬，今天进行调试的时候发现了这个异常，似乎是多线程导致的问题
java.lang.IllegalStateException: The remote endpoint was in state [TEXT_PARTIAL_WRITING] which is an invalid state for called method
![image](https://github.com/Linyuzai/concept/assets/36877983/538ed9d3-f946-4d7f-85a0-f99e3adea277)
平常使用websocket发送消息都会使用synchronized 
```java
public void send(String message) throws IOException {
        synchronized (session) {
            this.session.getBasicRemote().sendText(message);
        }
    }
```
我翻看了一下源码好像并没有进行处理😥😥

**Comment by Linyuzai** [comment]
> 大佬，今天进行调试的时候发现了这个异常，似乎是多线程导致的问题 java.lang.IllegalStateException: The remote endpoint was in state [TEXT_PARTIAL_WRITING] which is an invalid state for called method ![image](https://user-images.githubusercontent.com/36877983/250435023-538ed9d3-f946-4d7f-85a0-f99e3adea277.png) 平常使用websocket发送消息都会使用synchronized
> 
> ```java
> public void send(String message) throws IOException {
>         synchronized (session) {
>             this.session.getBasicRemote().sendText(message);
>         }
>     }
> ```
> 
> 我翻看了一下源码好像并没有进行处理😥😥

了解了，我还以为Spring封装的没这问题，我加一下

**Comment by chuchushijingxi** [comment]
> > 大佬，今天进行调试的时候发现了这个异常，似乎是多线程导致的问题 java.lang.IllegalStateException: The remote endpoint was in state [TEXT_PARTIAL_WRITING] which is an invalid state for called method ![image](https://user-images.githubusercontent.com/36877983/250435023-538ed9d3-f946-4d7f-85a0-f99e3adea277.png) 平常使用websocket发送消息都会使用synchronized
> > ```java
> > public void send(String message) throws IOException {
> >         synchronized (session) {
> >             this.session.getBasicRemote().sendText(message);
> >         }
> >     }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 我翻看了一下源码好像并没有进行处理😥😥
> 
> 了解了，我还以为Spring封装的没这问题，我加一下

嗯嗯

**Comment by Linyuzai** [comment]
> > > 大佬，今天进行调试的时候发现了这个异常，似乎是多线程导致的问题 java.lang.IllegalStateException: The remote endpoint was in state [TEXT_PARTIAL_WRITING] which is an invalid state for called method ![image](https://user-images.githubusercontent.com/36877983/250435023-538ed9d3-f946-4d7f-85a0-f99e3adea277.png) 平常使用websocket发送消息都会使用synchronized
> > > ```java
> > > public void send(String message) throws IOException {
> > >         synchronized (session) {
> > >             this.session.getBasicRemote().sendText(message);
> > >         }
> > >     }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 我翻看了一下源码好像并没有进行处理😥😥
> > 
> > 
> > 了解了，我还以为Spring封装的没这问题，我加一下
> 
> 嗯嗯

升到1.1.2试一下

**Comment by chuchushijingxi** [comment]
> > > > 大佬，今天进行调试的时候发现了这个异常，似乎是多线程导致的问题 java.lang.IllegalStateException: The remote endpoint was in state [TEXT_PARTIAL_WRITING] which is an invalid state for called method ![image](https://user-images.githubusercontent.com/36877983/250435023-538ed9d3-f946-4d7f-85a0-f99e3adea277.png) 平常使用websocket发送消息都会使用synchronized
> > > > ```java
> > > > public void send(String message) throws IOException {
> > > >         synchronized (session) {
> > > >             this.session.getBasicRemote().sendText(message);
> > > >         }
> > > >     }
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 我翻看了一下源码好像并没有进行处理😥😥
> > > 
> > > 
> > > 了解了，我还以为Spring封装的没这问题，我加一下
> > 
> > 
> > 嗯嗯
> 
> 升到1.1.2试一下

好的，谢谢大佬
