### ISSUE TITLE
websocket close问题

### ISSUE THREAD

**Issue by chuchushijingxi** [Linyuzai/concept#14]
![image](https://github.com/Linyuzai/concept/assets/36877983/2e7cc6f2-c21b-4b48-9011-42159b58e02e)
2.0.0版本直接传字符串进行关闭会报错。直接使用 connection.close(); 不会

**Comment by Linyuzai** [comment]
> ![image](https://user-images.githubusercontent.com/36877983/264544778-2e7cc6f2-c21b-4b48-9011-42159b58e02e.png)
> 2.0.0版本直接传字符串进行关闭会报错。直接使用 connection.close(); 不会

因为这个最后调用的是 Spring 的接口，所以需要传`CloseStatus`对象，你可以自己`new`一个，我这边因为`Servlet`和`Reactive`还有`Netty`等不同的连接对象需要传入的值不一样所以使用`Object`做兼容而已

**Comment by Linyuzai** [comment]
> ![image](https://user-images.githubusercontent.com/36877983/264544778-2e7cc6f2-c21b-4b48-9011-42159b58e02e.png)
> 2.0.0版本直接传字符串进行关闭会报错。直接使用 connection.close(); 不会

2.1.0版本处理了兼容问题不会再报错
