### ISSUE TITLE
concept-router-spring-boot-starter

### ISSUE THREAD

**Issue by 18767170861** [Linyuzai/concept#15]
SpringCloud:Hoxton.SR12 + SpringBoot:2.3.12.RELEASE + nacos + Gateway
error: Field propertiesFactory in org.springframework.cloud.netflix.ribbon.RibbonClientConfiguration required a bean of type 'org.springframework.cloud.netflix.ribbon.PropertiesFactory' that could not be found.

**Comment by Linyuzai** [comment]
> SpringCloud:Hoxton.SR12 + SpringBoot:2.3.12.RELEASE + nacos + Gateway
> error: Field propertiesFactory in org.springframework.cloud.netflix.ribbon.RibbonClientConfiguration required a bean of type 'org.springframework.cloud.netflix.ribbon.PropertiesFactory' that could not be found.

我这边测试下来没有你说的那个问题，SpringCloud:Hoxton.SR12 + SpringBoot:2.3.12.RELEASE + SpringCloudAlibaba2.2.6. RELEASE + Gateway，你可以看一下`org.springframework.cloud:spring-cloud-netflix-ribbon`是哪个版本，我的是`2.2.9. RELEASE`，里面的`RibbonAutoConfiguration`应该有注入`PropertiesFactory`
