### ISSUE TITLE
服务端如何接收消息，将消息用中间件转发等代码demo

### ISSUE THREAD

**Issue by hq1148365306** [Linyuzai/concept#17]
服务端如何接收消息，将消息用中间件转发等代码demo

**Comment by Linyuzai** [comment]
> 服务端如何接收消息，将消息用中间件转发等代码demo

Wiki里面应该都有写，用 NettyMessageHandler 和 WebSocketMessageHandler 来接收消息

**Comment by hq1148365306** [comment]
ok,已经看到了，在调试
