### ISSUE TITLE
连接websocket，服务器消息响应了就立马发生错误: undefined Websocket连接已断开！

### ISSUE THREAD

**Issue by Mrzedward** [Linyuzai/concept#18]
![image](https://github.com/Linyuzai/concept/assets/29618316/e09cfb3d-23cf-49c2-a5d8-d6fb9390164c)
![image](https://github.com/Linyuzai/concept/assets/29618316/8d2f0a1f-f005-4a6e-b5fd-3ab10c2f3f5c)

**Comment by Linyuzai** [comment]
> ![image](https://user-images.githubusercontent.com/29618316/266245414-e09cfb3d-23cf-49c2-a5d8-d6fb9390164c.png)
> ![image](https://user-images.githubusercontent.com/29618316/266245489-8d2f0a1f-f005-4a6e-b5fd-3ab10c2f3f5c.png)

默认的连接地址是：ws(s)://{服务的地址}/concept-websocket/{自定义路径}
Controller里面定义的是http啊，ws肯定连不上啊

**Comment by Mrzedward** [comment]
明白了，感谢

**Comment by Mrzedward** [comment]
> > ![image](https://user-images.githubusercontent.com/29618316/266245414-e09cfb3d-23cf-49c2-a5d8-d6fb9390164c.png)
> > ![image](https://user-images.githubusercontent.com/29618316/266245489-8d2f0a1f-f005-4a6e-b5fd-3ab10c2f3f5c.png)
> 
> 默认的连接地址是：ws(s)://{服务的地址}/concept-websocket/{自定义路径} Controller里面定义的是http啊，ws肯定连不上啊

用ServerEndpoint标记了，自己写的测试接口，为什么生效呢？
