### ISSUE TITLE
当nacos多实例测试的时候会出现LBWebSocket >> Exception occurred

### ISSUE THREAD

**Issue by Mrzedward** [Linyuzai/concept#19]
![image](https://github.com/Linyuzai/concept/assets/29618316/3a56b2a7-0947-413e-8321-25e2dbff72f8)
当在nacos注册了多实例的服务偶尔回去先这个错误。

**Comment by Linyuzai** [comment]
> ![image](https://user-images.githubusercontent.com/29618316/266932377-3a56b2a7-0947-413e-8321-25e2dbff72f8.png)
> 当在nacos注册了多实例的服务偶尔回去先这个错误。

了解了，你这边是在做什么操作的时候会触发还是说没有任何操作

**Comment by Mrzedward** [comment]
> > ![image](https://user-images.githubusercontent.com/29618316/266932377-3a56b2a7-0947-413e-8321-25e2dbff72f8.png)
> > 当在nacos注册了多实例的服务偶尔回去先这个错误。
> 
> 了解了，你这边是在做什么操作的时候会触发还是说没有任何操作

我在nacos上注册了两个实例，然后通过gateway去调用，偶尔就会出现。

**Comment by Mrzedward** [comment]
> > > ![image](https://user-images.githubusercontent.com/29618316/266932377-3a56b2a7-0947-413e-8321-25e2dbff72f8.png)
> > > 当在nacos注册了多实例的服务偶尔回去先这个错误。
> > 
> > 
> > 了解了，你这边是在做什么操作的时候会触发还是说没有任何操作
> 
> 我在nacos上注册了两个实例，然后通过gateway去调用，偶尔就会出现。

![image](https://github.com/Linyuzai/concept/assets/29618316/5c566c81-af7f-4267-a852-c427dfc39a89)
zhe这是我自定义的ws接口

**Comment by Linyuzai** [comment]
> > > > ![image](https://user-images.githubusercontent.com/29618316/266932377-3a56b2a7-0947-413e-8321-25e2dbff72f8.png)
> > > > 当在nacos注册了多实例的服务偶尔回去先这个错误。
> > > 
> > > 
> > > 了解了，你这边是在做什么操作的时候会触发还是说没有任何操作
> > 
> > 
> > 我在nacos上注册了两个实例，然后通过gateway去调用，偶尔就会出现。
> 
> ![image](https://user-images.githubusercontent.com/29618316/266939368-5c566c81-af7f-4267-a852-c427dfc39a89.png) zhe这是我自定义的ws接口

你有加@OnMessage吗，如果你自己处理消息的话，也需要将接收到的PongMessage传给concept，不然连接的心跳信息更新不了

**Comment by Mrzedward** [comment]
> > > > > ![image](https://user-images.githubusercontent.com/29618316/266932377-3a56b2a7-0947-413e-8321-25e2dbff72f8.png)
> > > > > 当在nacos注册了多实例的服务偶尔回去先这个错误。
> > > > 
> > > > 
> > > > 了解了，你这边是在做什么操作的时候会触发还是说没有任何操作
> > > 
> > > 
> > > 我在nacos上注册了两个实例，然后通过gateway去调用，偶尔就会出现。
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/29618316/266939368-5c566c81-af7f-4267-a852-c427dfc39a89.png) zhe这是我自定义的ws接口
> 
> 你有加@OnMessage吗，如果你自己处理消息的话，也需要将接收到的PongMessage传给concept，不然连接的心跳信息更新不了

![image](https://github.com/Linyuzai/concept/assets/29618316/d33f927e-011f-4cca-926c-32d31c52e7a2)
加了@OnMessage的

**Comment by Linyuzai** [comment]
能打断点看到具体的报错的连接里面的数据吗

**Comment by Linyuzai** [comment]
> 能打断点看到具体的报错的连接里面的数据吗

就是哪个连接报错的

**Comment by Mrzedward** [comment]
> > 能打断点看到具体的报错的连接里面的数据吗
> 
> 就是哪个连接报错的

因为我一直掉我这个接口，然后参数也一样，心跳超时了，session.close((CloseReason) reason);这里报错不能转换。

**Comment by Linyuzai** [comment]
> > > 能打断点看到具体的报错的连接里面的数据吗
> > 
> > 
> > 就是哪个连接报错的
> 
> 因为我一直掉我这个接口，然后参数也一样，心跳超时了，session.close((CloseReason) reason);这里报错不能转换。

2.1.0的版本处理了强转异常，不过不知道你那边为什么会出现心跳超超时，可以看看接收到ping之后有没有回pong
