### ISSUE TITLE
动态加载插件，无法加载mysql驱动

### ISSUE THREAD

**Issue by yangxing19930210** [Linyuzai/concept#2]
![image](https://user-images.githubusercontent.com/25998610/194845151-3f561174-60c3-4c9a-9b3f-b844df534403.png)

**Comment by Linyuzai** [comment]
看报错，More than one plugin matched，应该是匹配到了多个，可以试一下用List接收，最好是能贴一下方法onPluginExtract的参数

**Comment by yangxing19930210** [comment]
> 看报错，多于一个插件匹配，应该是匹配到了多个，可以试一下用List接收，最好是能贴一下方法onPluginExtract的参数

谢谢大佬，确实是有多个参数然后回调没匹配上，请问有这块的设计思路文档么？想参考下

**Comment by Linyuzai** [comment]
可以看看wiki，https://github.com/Linyuzai/concept/wiki/Concept-Plugin，有介绍解析流程还有用法

**Comment by Linyuzai** [comment]
> > 看报错，多于一个插件匹配，应该是匹配到了多个，可以试一下用List接收，最好是能贴一下方法onPluginExtract的参数
> 
> 谢谢大佬，确实是有多个参数然后回调没匹配上，请问有这块的设计思路文档么？想参考下

可以看看wiki，有介绍解析流程还有用法，https://github.com/Linyuzai/concept/wiki/Concept-Plugin

**Comment by yangxing19930210** [comment]
> > > 看报错，多于一个插件匹配，应该是匹配到了多个，可以试一下用List接收，最好是能贴一下方法onPluginExtract的参数
> > 
> > 
> > 谢谢大佬，确实是有多个参数然后回调没匹配上，请问有这块的设计思路文档么？想参考下
> 
> 可以看看wiki，有介绍解析流程还有用法，https://github.com/Linyuzai/concept/wiki/Concept-Plugin

谢谢
