### ISSUE TITLE
找不到文件时会返回一个压缩包

### ISSUE THREAD

**Issue by tzraeq** [Linyuzai/concept#20]
刚刚试了concept-download-spring-boot-starter的1.2.2版本，@Download注解什么都不写，方法返回 file:前缀的字符串，路径对应的文件不存在，结果得到了一个zip，里面包含一个文件，内容为空

**Comment by Linyuzai** [comment]
> 刚刚试了concept-download-spring-boot-starter的1.2.2版本，@Download注解什么都不写，方法返回 file:前缀的字符串，路径对应的文件不存在，结果得到了一个zip，里面包含一个文件，内容为空

了解了，你这边的功能需求会希望在这种情况下需要有一个怎么样的解决方案

**Comment by Linyuzai** [comment]
2.0.0 版本判断了文件是否存在 https://github.com/Linyuzai/concept/wiki/Concept-Download-2
