### ISSUE TITLE
@download注解，建议在文档中说明需要引用spring-aop包，或者在依赖中添加

### ISSUE THREAD

**Issue by heyefu19920626** [Linyuzai/concept#21]
如果没有引入spring-aop系列包，download注解实际上不生效的
https://github.com/Linyuzai/concept/wiki/Concept-Download

**Comment by Linyuzai** [comment]
> 如果没有引入spring-aop系列包，download注解实际上不生效的
> https://github.com/Linyuzai/concept/wiki/Concept-Download

已在Wiki中添加
