### ISSUE TITLE
springboot3.0 集成rabbit订阅兼容问题 concept-netty-loadbalance-spring-boot-starter 

### ISSUE THREAD

**Issue by fenfeiyunluo** [Linyuzai/concept#23]
AcknowledgeRabbitListenerEndpoint 实现的RabbitListenerEndpoint 这个接口在springboot3.0 增加了一个方法
	/**
	 * Whether this endpoint is for a batch listener.
	 * @return {@link Boolean#TRUE} if batch.
	 * @since 3.0
	 */
	@Nullable
	Boolean getBatchListener();

**Comment by Linyuzai** [comment]
> AcknowledgeRabbitListenerEndpoint 实现的RabbitListenerEndpoint 这个接口在springboot3.0 增加了一个方法
> /**
> * Whether this endpoint is for a batch listener.
> * @return {@link Boolean#TRUE} if batch.
> * @SInCE 3.0
> */
> @nullable
> Boolean getBatchListener();

2.3.0版本已兼容
