### ISSUE TITLE
使用RABBIT_FANOUT转发消息解析异常

### ISSUE THREAD

**Issue by fenfeiyunluo** [Linyuzai/concept#26]
依赖名称：concept-netty-loadbalance-spring-boot-starter

依赖版本：2.3.0 、 2.3.2

问题描述：使用rabbimq转发UserMessage消息 BaseMessageCodecAdapter.getForwardMessageDecoder 方法下的 JacksonForwardMessageDecoder.readTree(Object message)抛出异常。mq转发消息Object message 类型（org.springframework.amqp.core.Message）

代码示例：
修复重写方法：
    @SneakyThrows
    protected JsonNode readTree(Object message) {
        if (message instanceof String strMessage) {
            return objectMapper.readTree(strMessage);
        }
        if (message instanceof Message mqMessage) {
            return objectMapper.readTree((mqMessage.getBody()));
        }
        if (message instanceof ByteBuffer byteBuffer) {
            return objectMapper.readTree(byteBuffer.array());
        }
        if (message instanceof byte[]) {
            return objectMapper.readTree((byte[]) message);
        }
        throw new MessageDecodeException(message);
    }

**Comment by Linyuzai** [comment]
> 依赖名称：concept-netty-loadbalance-spring-boot-starter
> 
> 依赖版本：2.3.0 、 2.3.2
> 
> 问题描述：使用rabbimq转发UserMessage消息 BaseMessageCodecAdapter.getForwardMessageDecoder 方法下的 JacksonForwardMessageDecoder.readTree(Object message)抛出异常。mq转发消息Object message 类型（org.springframework.amqp.core.Message）
> 
> 代码示例： 修复重写方法： @SneakyThrows protected JsonNode readTree(Object message) { if (message instanceof String strMessage) { return objectMapper.readTree(strMessage); } if (message instanceof Message mqMessage) { return objectMapper.readTree((mqMessage.getBody())); } if (message instanceof ByteBuffer byteBuffer) { return objectMapper.readTree(byteBuffer.array()); } if (message instanceof byte[]) { return objectMapper.readTree((byte[]) message); } throw new MessageDecodeException(message); }

我这边 2.3.2 没有复现，rabbitmq message 的处理在 RabbitMessageCodecAdapter，能提供更详细的信息吗
