### ISSUE TITLE
启动多个服务实例，实例之间无法连接

### ISSUE THREAD

**Issue by JinZuliu0120** [Linyuzai/concept#27]
依赖名称：
concept-websocket-loadbalance-spring-boot-starter
依赖版本：
<dependency>
	<groupId>com.github.linyuzai</groupId>
	<artifactId>concept-websocket-loadbalance-spring-boot-starter</artifactId>
	<version>2.3.2</version>
</dependency>
问题描述：
      集成后部署一台服务（一个服务实例），流程没有问题，但是部署多台服务时，后端报错：
      WebSocketConnectionManager-[136] - Connecting to WebSocket at ws://192.168.7.82:8197/concept-websocket-subscriber
       [SimpleAsyncTaskExecutor-1] ERROR o.s.web.socket.client.WebSocketConnectionManager-[150] - Failed to connect
      javax.websocket.DeploymentException: The HTTP response from the server [404] did not permit the HTTP upgrade to WebSocket
	at org.apache.tomcat.websocket.WsWebSocketContainer.connectToServerRecursive(WsWebSocketContainer.java:430)
	at org.apache.tomcat.websocket.WsWebSocketContainer.connectToServer(WsWebSocketContainer.java:185)
	at org.springframework.web.socket.client.standard.StandardWebSocketClient.lambda$doHandshakeInternal$0(StandardWebSocketClient.java:151)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:750)
代码示例：

    1：添加依赖
   	
		<dependency>
			<groupId>com.github.linyuzai</groupId>
			<artifactId>concept-websocket-loadbalance-spring-boot-starter</artifactId>
			<version>2.3.2</version>
		</dependency>

		
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-websocket</artifactId>
		</dependency>

      2：启动类增加 @EnableWebSocketLoadBalanceConcept
         /**
         * 程序启动类
         * @author jinzl@esa2000.com
         */
        @EnableWebSocketLoadBalanceConcept
        @EnableRetry
        @EnableAsync
        @EnableFeignClients
        @SpringBootApplication
        @EnableDiscoveryClient
        public class AztContractApplication {
        
	        public static void main(String[] args) {
		        AztSpringApplication.run(AztContractApplication.class, args);
	        }
        
        }
        

      3：配置文件

concept:
  websocket:
    type: auto #JAVAX/SERVLET/REACTIVE，AUTO自动适配，默认AUTO
    server: #服务配置
      default-endpoint: #默认端点
        enabled: true #是否启用默认端点，默认true
        prefix: concept-websocket #前缀，默认'/concept-websocket/'
        path-selector: #Path选择器
          enabled: false #是否启用Path选择器，默认false
        user-selector: #User选择器
          enabled: true #是否启用User选择器，默认false
      message:
        retry:
          times: 0 #客户端重试次数，默认不重试
          period: 0 #客户端重试间隔，单位ms，默认0ms
      heartbeat: #心跳配置
        enabled: true #是否启用心跳，默认true
        period: 60000 #心跳间隔，单位ms，默认1分钟
        timeout: 210000 #超时时间，单位ms，默认3.5分钟，3次心跳间隔
    load-balance: #负载均衡（转发）配置
      subscriber-master: websocket #主订阅器，默认 websocket
      subscriber-slave: none #从订阅器，默认无
      message:
        retry:
          times: 0 #转发重试次数，默认不重试
          period: 0 #转发重试间隔，单位ms，默认0ms
      monitor: #监控配置
        enabled: true #是否启用监控，默认true
        period: 30000 #轮训间隔，单位ms，默认30s
        logger: false #是否启用日志，默认false
      heartbeat: #心跳配置
        enabled: true #是否启用心跳，默认true
        period: 60000 #心跳间隔，单位ms，默认1分钟
        timeout: 210000 #超时时间，单位ms，默认3.5分钟，3次心跳间隔
    executor:
      thread-pool-size: 1 #线程池大小，默认1

**Comment by Linyuzai** [comment]
你的服务地址是192.168.7.82:8197这个吗

**Comment by JinZuliu0120** [comment]
服务时注册到nacos中的，部署了两台服务 分别是 192.168.7.82:8197，192.168.1.205:8197，都是局域网，麻烦帮看下指导下这个错误应该怎么处理，谢谢











金祖柳
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Linyuzai/concept"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月5日(星期二) 上午10:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Linyuzai/concept] 启动多个服务实例，实例之间无法连接 (Issue #27)





 
你的服务地址是192.168.7.82:8197这个吗

**Comment by Linyuzai** [comment]
两台服务器能互相连通吗，你在一台服务器上改个端口启动两个实例试试

**Comment by JinZuliu0120** [comment]
是一样的：










金祖柳
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Linyuzai/concept"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月5日(星期二) 中午12:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Linyuzai/concept] 启动多个服务实例，实例之间无法连接 (Issue #27)





 
两台服务器能互相连通吗，你在一台服务器上改个端口启动两个实例试试

**Comment by Linyuzai** [comment]
你的服务里面有添加什么拦截器吗，你试一下新建一个简单的项目，只引用这个依赖看行不行，或者你自己手动配置一个ws的连接地址，看能不能连上

**Comment by JinZuliu0120** [comment]
我的服务有服务名xxx ，但是那个获取端点我看getEndpoint默认是写死：/concept-websocket-subscriber，



public URI getUri(ConnectionServer server) {
    try {
        return new URI(this.getProtocol() + "://" + this.getHost(server) + ":" + this.getPort(server) + this.getEndpoint());
    } catch (Throwable var3) {
        throw var3;
    }
}




public String getEndpoint() {
    return "/concept-websocket-subscriber";
}


ws://192.168.7.27:8197/concept-websocket-subscriber




但是我的服务名比如是AAA，是不是应该连接ws://192.168.7.27:8197/AAA/concept-websocket-subscriber



金祖柳
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Linyuzai/concept"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月5日(星期二) 下午2:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Linyuzai/concept] 启动多个服务实例，实例之间无法连接 (Issue #27)





 
你的服务里面有添加什么拦截器吗，你试一下新建一个简单的项目，只引用这个依赖看行不行，或者你自己手动配置一个ws的连接地址，看能不能连上

**Comment by Linyuzai** [comment]
你的服务名是用spring.application.name配置的吗，这个和连接的uri没关系，有试过我上面说的吗，或者发一下你的代码和配置

**Comment by JinZuliu0120** [comment]
连接没报错了 ，但是一个客户端（浏览器）向后端建立连接之后，后端有两个服务，前段时A服务连接，A服务发送消息，前端能收到，B服务给前端发送同样的消息，前端有收到服务端回应，但是消息内容没用，是怎么回事

金祖柳
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Linyuzai/concept"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月5日(星期二) 晚上7:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Linyuzai/concept] 启动多个服务实例，实例之间无法连接 (Issue #27)





 
你的服务名是用spring.application.name配置的吗，这个和连接的uri没关系，有试过我上面说的吗，或者发一下你的代码和配置

**Comment by Linyuzai** [comment]
没有消息内容吗？你的消息是什么类型的，对象的话目前有个bug，不知道是不是你说的情况，你试下用字符串的消息

**Comment by Linyuzai** [comment]
> 没有消息内容吗？你的消息是什么类型的，对象的话目前有个bug，不知道是不是你说的情况，你试下用字符串的消息

2.3.3版本已经修复了发送对象消息转发为空的问题，你可以看下是不是还有问题

**Comment by JinZuliu0120** [comment]
是的，对象问题。谢谢，可以了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Linyuzai ***@***.***&gt;
发送时间: 2023年12月6日 17:44
收件人: Linyuzai/concept ***@***.***&gt;
抄送: JinZuliu0120 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [Linyuzai/concept] 启动多个服务实例，实例之间无法连接 (Issue #27)





  
没有消息内容吗？你的消息是什么类型的，对象的话目前有个bug，不知道是不是你说的情况，你试下用字符串的消息
  
2.3.3版本已经修复了发送对象消息转发为空的问题，你可以看下是不是还有问题
