### ISSUE TITLE
添加依赖后，Mac系统启动gateway时报文件创建错误

### ISSUE THREAD

**Issue by jc5337207** [Linyuzai/concept#3]
<img width="1415" alt="image" src="https://user-images.githubusercontent.com/23159732/204430799-dfcbcceb-1beb-41d3-b2d6-20ac2f03c779.png">
<img width="1223" alt="image" src="https://user-images.githubusercontent.com/23159732/204430888-e71736e9-328e-4e4f-9399-e6e3f44d6101.png">

**Comment by Linyuzai** [comment]
> <img alt="image" width="1415" src="https://user-images.githubusercontent.com/23159732/204430799-dfcbcceb-1beb-41d3-b2d6-20ac2f03c779.png">
> 
> <img alt="image" width="1223" src="https://user-images.githubusercontent.com/23159732/204430888-e71736e9-328e-4e4f-9399-e6e3f44d6101.png">

这个是默认使用本地文件来保存路由的数据，看报错应该是文件路径有问题，你可以打断点看下具体的文件路径，或者是用`concept.router.repository.local.path`来指定一个目录，这个路径的默认值是`new File(System.getProperty("user.home"), "concept/router").getAbsolutePath();`有可能有问题

**Comment by jc5337207** [comment]
修改配置后可以了，谢谢
