### ISSUE TITLE
异步回调转为同步返回

### ISSUE THREAD

**Issue by lsw1589034474** [Linyuzai/concept#32]
依赖名称：

依赖版本：

问题描述：使用异步回调转为同步返回包，通过kafka返回消息ID来唤醒线程，第一次请求正常，点击第二次就会报请求超时，设置超时时间为3秒，收到kakfa消息是在三秒内

异常堆栈：

代码示例：

**Comment by Linyuzai** [comment]
能贴一下代码吗

**Comment by lsw1589034474** [comment]
![image](https://github.com/Linyuzai/concept/assets/54879658/dc6b6bd1-40b7-4372-8ee1-35ad2fb899e4)
![image](https://github.com/Linyuzai/concept/assets/54879658/c3a215f3-ff8f-4f97-bd02-d59c2e22e5d4)

**Comment by Linyuzai** [comment]
SyncCaller里面起线程可能有问题，直接同步调feign试试

**Comment by Linyuzai** [comment]
是单体应用吗，还是做了负载均衡

**Comment by lsw1589034474** [comment]
是集群，哦，这点忽略了

**Comment by Linyuzai** [comment]
> 是集群，哦，这点忽略了

集群应该是有问题，除非能够做到哪个实例发就哪个实例接收

**Comment by lsw1589034474** [comment]
是的，存在分布式问题
