### ISSUE TITLE
发现发送消息会一直占用  发生java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by NixerSo5** [Linyuzai/concept#33]
依赖名称：
concept-websocket-loadbalance-spring-boot-starter
依赖版本：

com.github.linyuzai
concept-websocket-loadbalance-spring-boot-starter
2.3.2

**Comment by NixerSo5** [comment]
使用相同userid进行连接 开多个页面 的时候依然会重复占用

**Comment by Linyuzai** [comment]
是指发送过的消息对象一直不会释放吗？

**Comment by Linyuzai** [comment]
可以给一个能复现问题的demo吗

**Comment by NixerSo5** [comment]
[ws_servder (2).zip](https://github.com/Linyuzai/concept/files/14018720/ws_servder.2.zip)

**Comment by NixerSo5** [comment]
我是想如果是同一个uuid不应该使用同一个空间吗   是因为不同的session照成的  吗?

**Comment by NixerSo5** [comment]
> 我是想如果是同一个uuid不应该使用同一个空间吗 是因为不同的session照成的 吗?

userId

**Comment by Linyuzai** [comment]
> > 我是想如果是同一个uuid不应该使用同一个空间吗 是因为不同的session照成的 吗?
> 
> userId

同一个userId也可能是不同的session（每次打开连接都会生成一个新的session），你说的空间指的是什么意思

**Comment by NixerSo5** [comment]
> > > 我是想如果是同一个uuid不应该使用同一个空间吗 是因为不同的session照成的 吗?
> > 
> > 
> > userId
> 
> 同一个userId也可能是不同的session（每次打开连接都会生成一个新的session），你说的空间指的是什么意思

就是说我知道本来应该是和seesion有关的  然后我是想说如果是同一个userid  不应该把之前的断开  然后保留新打开的吗 
目前的感觉就是旧的没释放

**Comment by NixerSo5** [comment]
空间的描述不好  就是说缓冲区

**Comment by Linyuzai** [comment]
> > > > 我是想如果是同一个uuid不应该使用同一个空间吗 是因为不同的session照成的 吗?
> > > 
> > > 
> > > userId
> > 
> > 
> > 同一个userId也可能是不同的session（每次打开连接都会生成一个新的session），你说的空间指的是什么意思
> 
> 就是说我知道本来应该是和seesion有关的 然后我是想说如果是同一个userid 不应该把之前的断开 然后保留新打开的吗 目前的感觉就是旧的没释放

`同一个userid把之前的断开`这个应该是根据业务在上层控制的，并不会做在框架里面，如果你需要把之前的断开，可以监听连接打开的事件然后筛选userId相同的连接调用close方法关闭

**Comment by NixerSo5** [comment]
> > > > > 我是想如果是同一个uuid不应该使用同一个空间吗 是因为不同的session照成的 吗?
> > > > 
> > > > 
> > > > userId
> > > 
> > > 
> > > 同一个userId也可能是不同的session（每次打开连接都会生成一个新的session），你说的空间指的是什么意思
> > 
> > 
> > 就是说我知道本来应该是和seesion有关的 然后我是想说如果是同一个userid 不应该把之前的断开 然后保留新打开的吗 目前的感觉就是旧的没释放
> 
> `同一个userid把之前的断开`这个应该是根据业务在上层控制的，并不会做在框架里面，如果你需要把之前的断开，可以监听连接打开的事件然后筛选userId相同的连接调用close方法关闭

这个是可以的但是问题是 他也不会继续给同样的userid 发送相同的信息 所以才造成了我以为userid 同样会分开  我会从业务上来解决该问题  谢谢
