### ISSUE TITLE
如何主动关闭集群其它机器的 websocket 连接

### ISSUE THREAD

**Issue by chuchushijingxi** [Linyuzai/concept#36]
依赖名称：
concept-websocket-loadbalance-spring-boot-starter
依赖版本：
2.4.0
问题描述：
请问大佬要怎么断开集群中其它机器客户端的 websocket 连接呢？
集群中有 A B 两台机器，如何在 A 机器上断开客户端在 B 机器上的连接。
异常堆栈：

代码示例：

**Comment by Linyuzai** [comment]
目前没有这样的功能，只能关闭自己服务的连接，你可以A调用一下B，B关闭自己的连接

**Comment by chuchushijingxi** [comment]
> Owner

好的，谢谢
