### ISSUE TITLE
指定服务地址未生效

### ISSUE THREAD

**Issue by jc5337207** [Linyuzai/concept#4]
<img width="1676" alt="image" src="https://user-images.githubusercontent.com/23159732/204458631-3f4b0255-2c5a-4f5d-85cd-31134e8898b4.png">
<img width="1652" alt="image" src="https://user-images.githubusercontent.com/23159732/204458703-d3d461d9-aef4-4b46-93e4-c65dc2d87aa1.png">

指定服务地址未生效，请问还需要其他配置吗？

**Comment by Linyuzai** [comment]
> <img alt="image" width="1676" src="https://user-images.githubusercontent.com/23159732/204458631-3f4b0255-2c5a-4f5d-85cd-31134e8898b4.png">
> 
> <img alt="image" width="1652" src="https://user-images.githubusercontent.com/23159732/204458703-d3d461d9-aef4-4b46-93e4-c65dc2d87aa1.png">
> 
> 指定服务地址未生效，请问还需要其他配置吗？

你看下控制台有没有打印相关的日志

**Comment by jc5337207** [comment]
控制台有打印，是不是这个匹配路径的问题

<img width="1576" alt="image" src="https://user-images.githubusercontent.com/23159732/204460367-169fdcf8-cdf8-4ecd-88dc-f7ef7de456f3.png">

**Comment by Linyuzai** [comment]
> 控制台有打印，是不是这个匹配路径的问题
> 
> <img alt="image" width="1576" src="https://user-images.githubusercontent.com/23159732/204460367-169fdcf8-cdf8-4ecd-88dc-f7ef7de456f3.png">

你在路由上配置的是`system`为前缀的接口，`/user/list`肯定是匹配不上的

**Comment by jc5337207** [comment]
了解了，这边在做路由的时候把前缀全部默认去掉了

**Comment by jc5337207** [comment]
![Uploading image.png…]()
那请问配置了stripPrefix=1后能够使用您这个库么？

**Comment by jc5337207** [comment]
<img width="822" alt="image" src="https://user-images.githubusercontent.com/23159732/204466990-0bf3168f-c395-497c-b145-3054c1d0008d.png">

**Comment by Linyuzai** [comment]
> <img alt="image" width="822" src="https://user-images.githubusercontent.com/23159732/204466990-0bf3168f-c395-497c-b145-3054c1d0008d.png">

理论上应该可以，不过我没有单独测试过，路由规则是SpringGateway解析的，我这边只是处理解析之后的service和uri，并不是直接把前缀去掉，所以可视化页面上会有一列`匹配服务`用于指定对应的服务

**Comment by jc5337207** [comment]
最终还是配置了 spring.cloud.nacos.discovery.group
