### ISSUE TITLE
有没有demo

### ISSUE THREAD

**Issue by githubzhangfei** [Linyuzai/concept#5]
完全不会用呀，我有一个这样的需求，我在主程序里面写了一个接口，想在第二个程序里面实现这个接口，然后动态的加载到主程序里面，然后强制转换成主程序接口，他提示类型转换异常，查阅资料后估计是类加载器不一致导致的。不知道作者这个支持这种方式吗，或者说我应该怎么做。

**Comment by Linyuzai** [comment]
> 完全不会用呀，我有一个这样的需求，我在主程序里面写了一个接口，想在第二个程序里面实现这个接口，然后动态的加载到主程序里面，然后强制转换成主程序接口，他提示类型转换异常，查阅资料后估计是类加载器不一致导致的。不知道作者这个支持这种方式吗，或者说我应该怎么做。

要不你贴下代码，主程序和第二个程序的都贴下

**Comment by Linyuzai** [comment]
> 完全不会用呀，我有一个这样的需求，我在主程序里面写了一个接口，想在第二个程序里面实现这个接口，然后动态的加载到主程序里面，然后强制转换成主程序接口，他提示类型转换异常，查阅资料后估计是类加载器不一致导致的。不知道作者这个支持这种方式吗，或者说我应该怎么做。

wiki上也有写用法，https://github.com/Linyuzai/concept/wiki/Concept-Plugin
