### ISSUE TITLE
user模式有bug

### ISSUE THREAD

**Issue by zhuanghuijian** [Linyuzai/concept#7]
该模式不支持分布式。多实例发布消息有bug。客户端绑定的实例才能触达到客户端。

例如；相同用户打开两个页面（两个客户端，一个用户支持多端的需求，在手机或者电脑端打开相同的ws地址），一个连接到后端实例A，一个连接到后端实例B，如果在实例A发送消息，绑定实例A的客户端收到消息，绑定实例B的客户端收不到消息。反之一样。

send 和 sendPath 模式正常（支持分布式）

**Comment by Linyuzai** [comment]
> 该模式不支持分布式。多实例发布消息有bug。客户端绑定的实例才能触达到客户端。
> 
> 例如；相同用户打开两个页面（两个客户端，一个用户支持多端的需求，在手机或者电脑端打开相同的ws地址），一个连接到后端实例A，一个连接到后端实例B，如果在实例A发送消息，绑定实例A的客户端收到消息，绑定实例B的客户端收不到消息。反之一样。
> 
> send 和 sendPath 模式正常（支持分布式）

是用的`UserMessage`发送的消息吗，之前好像是默认用户是只有一个连接，所以如果本身服务匹配到了就不广播了

可以设置`UserMessage`的`broadcast`为`true`试试

```java
UserMessage message = ...
message.setBroadcast(true);
```
