### ISSUE TITLE
集群连接问题

### ISSUE THREAD

**Issue by chuchushijingxi** [Linyuzai/concept#9]
大佬，你好。
我在idea中启动了两个相同模块，端口不一样，都注册上nacos
![image](https://github.com/Linyuzai/concept/assets/36877983/9425e88b-1e02-44f2-99fb-bf1552cbc2b8)
这是网关的转发配置
![image](https://github.com/Linyuzai/concept/assets/36877983/e7840a5a-a96c-40d8-b6d5-55f503d9dd82)
两个都启动后连接出现了问题
![image](https://github.com/Linyuzai/concept/assets/36877983/aaa1f903-2b20-4d10-8b0b-c0f6036a8932)
拿到 ws 地址去测试发现是可以连接上的
![image](https://github.com/Linyuzai/concept/assets/36877983/eb838577-38bc-4707-9d4c-0ac2f5474819)

**Comment by Linyuzai** [comment]
> 大佬，你好。
> 我在idea中启动了两个相同模块，端口不一样，都注册上nacos
> ![image](https://user-images.githubusercontent.com/36877983/245338269-9425e88b-1e02-44f2-99fb-bf1552cbc2b8.png)
> 两个都启动后连接出现了问题
> ![image](https://user-images.githubusercontent.com/36877983/245338390-aaa1f903-2b20-4d10-8b0b-c0f6036a8932.png)
> 拿到 ws 地址去测试发现是可以连接上的
> ![image](https://user-images.githubusercontent.com/36877983/245338502-eb838577-38bc-4707-9d4c-0ac2f5474819.png)

你服务的ip，192.168.187.1 这种类型应该是启动了虚拟网卡之类的吧，关掉试试，你看下ifconfig，正常来说不会是这样的ip，而且你测试的那个不是断开连接了吗

**Comment by chuchushijingxi** [comment]
> > 大佬，你好。
> > 我在idea中启动了两个相同模块，端口不一样，都注册上nacos
> > ![image](https://user-images.githubusercontent.com/36877983/245338269-9425e88b-1e02-44f2-99fb-bf1552cbc2b8.png)
> > 两个都启动后连接出现了问题
> > ![image](https://user-images.githubusercontent.com/36877983/245338390-aaa1f903-2b20-4d10-8b0b-c0f6036a8932.png)
> > 拿到 ws 地址去测试发现是可以连接上的
> > ![image](https://user-images.githubusercontent.com/36877983/245338502-eb838577-38bc-4707-9d4c-0ac2f5474819.png)
> 
> 你服务的ip，192.168.187.1 这种类型应该是启动了虚拟网卡之类的吧，关掉试试，你看下ifconfig，正常来说不会是这样的ip，而且你测试的那个不是断开连接了吗

替换成ifconfig中的 IPV4地址也是一样
![image](https://github.com/Linyuzai/concept/assets/36877983/7a703afa-c9e1-4e42-8058-924c4d7ad3ef)
![image](https://github.com/Linyuzai/concept/assets/36877983/556704e1-2875-439e-ba51-e2839ccb016a)
测试的连接是可以的，是我自己手动断开的
![image](https://github.com/Linyuzai/concept/assets/36877983/8fcc7201-106e-435a-839d-4043e5d30b17)

**Comment by Linyuzai** [comment]
我看了一下，我异常是在这里抛出的
```java
static {
        ClassLoader loader = ServletWebSocketConnectionSubscriber.class.getClassLoader();
        javaxPresent = ClassUtils.isPresent("org.apache.tomcat.websocket.server.WsHttpUpgradeHandler", loader);
        jettyPresent = ClassUtils.isPresent("org.eclipse.jetty.websocket.client.WebSocketClient", loader);
    }
public WebSocketClient newWebSocketClient() {
        if (jettyPresent) {
            return new JettyWebSocketClient();
        } else if (javaxPresent) {
            //TODO WebSocketContainer
            return new StandardWebSocketClient();
        } else {
            throw new WebSocketLoadBalanceException("No suitable client found");
        }
    }
```
你的web容器用的是tomcat吗，什么版本，还是用的其他容器

**Comment by chuchushijingxi** [comment]
> 我看了一下，我异常是在这里抛出的
> 
> ```java
> static {
>         ClassLoader loader = ServletWebSocketConnectionSubscriber.class.getClassLoader();
>         javaxPresent = ClassUtils.isPresent("org.apache.tomcat.websocket.server.WsHttpUpgradeHandler", loader);
>         jettyPresent = ClassUtils.isPresent("org.eclipse.jetty.websocket.client.WebSocketClient", loader);
>     }
> public WebSocketClient newWebSocketClient() {
>         if (jettyPresent) {
>             return new JettyWebSocketClient();
>         } else if (javaxPresent) {
>             //TODO WebSocketContainer
>             return new StandardWebSocketClient();
>         } else {
>             throw new WebSocketLoadBalanceException("No suitable client found");
>         }
>     }
> ```
> 
> 你的web容器用的是tomcat吗，什么版本，还是用的其他容器

用的 undertow ，springboot 2.7.11
我是需要自己重写一个Client的连接吗😥

**Comment by Linyuzai** [comment]
> > 我看了一下，我异常是在这里抛出的
> > ```java
> > static {
> >         ClassLoader loader = ServletWebSocketConnectionSubscriber.class.getClassLoader();
> >         javaxPresent = ClassUtils.isPresent("org.apache.tomcat.websocket.server.WsHttpUpgradeHandler", loader);
> >         jettyPresent = ClassUtils.isPresent("org.eclipse.jetty.websocket.client.WebSocketClient", loader);
> >     }
> > public WebSocketClient newWebSocketClient() {
> >         if (jettyPresent) {
> >             return new JettyWebSocketClient();
> >         } else if (javaxPresent) {
> >             //TODO WebSocketContainer
> >             return new StandardWebSocketClient();
> >         } else {
> >             throw new WebSocketLoadBalanceException("No suitable client found");
> >         }
> >     }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 你的web容器用的是tomcat吗，什么版本，还是用的其他容器
> 
> 用的 undertow ，springboot 2.7.11 我是需要自己重写一个Client的连接吗😥

你可以继承`ServletWebSocketConnectionSubscriber`重写`newWebSocketClient`方法注入到`Spring`里面，或者等我加一下`Undertow`的

我之前以为国内没什么人用`Undertow`就没加了。。。

**Comment by chuchushijingxi** [comment]
> 你可以继承`ServletWebSocketConnectionSubscriber`重写`newWebSocketClient`方法注入到`Spring`里面，或者等我加一下`Undertow`的
> 
> 我之前以为国内没什么人用`Undertow`就没加了。。。

谢谢大佬的回复，😁

**Comment by chuchushijingxi** [comment]
> > 你可以继承`ServletWebSocketConnectionSubscriber`重写`newWebSocketClient`方法注入到`Spring`里面，或者等我加一下`Undertow`的
> > 我之前以为国内没什么人用`Undertow`就没加了。。。
> 
> 谢谢大佬的回复，因为是新项目，想尝试一下较新的版本😁

大佬能麻烦你加一下吗，我不太搞得定😭😭

**Comment by chuchushijingxi** [comment]
> > > 我看了一下，我异常是在这里抛出的
> > > ```java
> > > static {
> > >         ClassLoader loader = ServletWebSocketConnectionSubscriber.class.getClassLoader();
> > >         javaxPresent = ClassUtils.isPresent("org.apache.tomcat.websocket.server.WsHttpUpgradeHandler", loader);
> > >         jettyPresent = ClassUtils.isPresent("org.eclipse.jetty.websocket.client.WebSocketClient", loader);
> > >     }
> > > public WebSocketClient newWebSocketClient() {
> > >         if (jettyPresent) {
> > >             return new JettyWebSocketClient();
> > >         } else if (javaxPresent) {
> > >             //TODO WebSocketContainer
> > >             return new StandardWebSocketClient();
> > >         } else {
> > >             throw new WebSocketLoadBalanceException("No suitable client found");
> > >         }
> > >     }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 你的web容器用的是tomcat吗，什么版本，还是用的其他容器
> > 
> > 
> > 用的 undertow ，springboot 2.7.11 我是需要自己重写一个Client的连接吗😥
> 
> 你可以继承`ServletWebSocketConnectionSubscriber`重写`newWebSocketClient`方法注入到`Spring`里面，或者等我加一下`Undertow`的
> 
> 我之前以为国内没什么人用`Undertow`就没加了。。。

大佬能麻烦你加一下吗，我不太搞得定😭😭

**Comment by Linyuzai** [comment]
> > > > 我看了一下，我异常是在这里抛出的
> > > > ```java
> > > > static {
> > > >         ClassLoader loader = ServletWebSocketConnectionSubscriber.class.getClassLoader();
> > > >         javaxPresent = ClassUtils.isPresent("org.apache.tomcat.websocket.server.WsHttpUpgradeHandler", loader);
> > > >         jettyPresent = ClassUtils.isPresent("org.eclipse.jetty.websocket.client.WebSocketClient", loader);
> > > >     }
> > > > public WebSocketClient newWebSocketClient() {
> > > >         if (jettyPresent) {
> > > >             return new JettyWebSocketClient();
> > > >         } else if (javaxPresent) {
> > > >             //TODO WebSocketContainer
> > > >             return new StandardWebSocketClient();
> > > >         } else {
> > > >             throw new WebSocketLoadBalanceException("No suitable client found");
> > > >         }
> > > >     }
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 你的web容器用的是tomcat吗，什么版本，还是用的其他容器
> > > 
> > > 
> > > 用的 undertow ，springboot 2.7.11 我是需要自己重写一个Client的连接吗😥
> > 
> > 
> > 你可以继承`ServletWebSocketConnectionSubscriber`重写`newWebSocketClient`方法注入到`Spring`里面，或者等我加一下`Undertow`的
> > 我之前以为国内没什么人用`Undertow`就没加了。。。
> 
> 大佬能麻烦你加一下吗，我不太搞得定😭😭

升到`1.1.1`版本试下

**Comment by chuchushijingxi** [comment]
> > > > 我看了一下，我异常是在这里抛出的
> > > > ```java
> > > > static {
> > > >         ClassLoader loader = ServletWebSocketConnectionSubscriber.class.getClassLoader();
> > > >         javaxPresent = ClassUtils.isPresent("org.apache.tomcat.websocket.server.WsHttpUpgradeHandler", loader);
> > > >         jettyPresent = ClassUtils.isPresent("org.eclipse.jetty.websocket.client.WebSocketClient", loader);
> > > >     }
> > > > public WebSocketClient newWebSocketClient() {
> > > >         if (jettyPresent) {
> > > >             return new JettyWebSocketClient();
> > > >         } else if (javaxPresent) {
> > > >             //TODO WebSocketContainer
> > > >             return new StandardWebSocketClient();
> > > >         } else {
> > > >             throw new WebSocketLoadBalanceException("No suitable client found");
> > > >         }
> > > >     }
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > 你的web容器用的是tomcat吗，什么版本，还是用的其他容器
> > > 
> > > 
> > > 用的 undertow ，springboot 2.7.11 我是需要自己重写一个Client的连接吗😥
> > 
> > 
> > 你可以继承`ServletWebSocketConnectionSubscriber`重写`newWebSocketClient`方法注入到`Spring`里面，或者等我加一下`Undertow`的
> > 我之前以为国内没什么人用`Undertow`就没加了。。。
> 
> 大佬能麻烦你加一下吗，我不太搞得定😭😭

已经好啦，太强了！😁
